Repository ootd-zip/client, pull requests merged in 2024-03, with the labels that each got.

#155 옷 관련 API 연동 및 수정
  apis/_api/cloth.ts
  apis/_api/type.ts
  apis/_service/user.service.ts
  apis/domain/Cloth/ClothApi.tsx
  components/DetailCloth/DeleteAlert/index.tsx
  components/DetailCloth/DetailClothDetailInfo/index.tsx
  components/Domain/AddCloth/WhereToBuyModal/index.tsx
  components/Domain/OOTD/SimilarOOTD/index.tsx
  components/Domain/OOTD/UserCloth/style.tsx
  components/Input/Modal/index.tsx
  components/Input/ReadOnly/index.tsx
  components/Input/ReadOnly/style.tsx
  components/Input/Text/index.tsx
  components/Input/Text/style.tsx
  pages/AddCloth/BasicInfoSecond/index.tsx
  pages/AddCloth/index.tsx
  pages/Cloth/[...ClothNumber].tsx
  pages/EditCloth/BasicInfo/index.tsx
  pages/EditCloth/[...ClothNumber].tsx
Labels: 🐞 버그, ⚙ 기능개발

#157 OOTD API 수정 및 추가연동
  apis/_api/ootd.ts
  apis/_api/type.ts
  apis/_service/user.service.ts
  apis/domain/OOTD/OOTDApi.tsx
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/index.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Domain/OOTD/FixModal/index.tsx
  components/Posting/index.tsx
  pages/AddOOTD/ClothTag/index.tsx
  pages/AddOOTD/WriteOOTD/index.tsx
  pages/EditOOTD/[...OOTDNumber].tsx
  pages/OOTD/[...OOTDNumber].tsx
Labels: ⚙ 기능개발

#161 BottomNavBar 추가 버튼 수정
  components/BottomNavBar/index.tsx
  public/images/FilledPlusSquare.svg
Labels: 🐞 버그

#159 마이페이지 css 수정
  components/ClothCategory/index.tsx
  components/ColorList/index.tsx
  components/ColorList/style.tsx
  components/Domain/AddCloth/ColorModal/index.tsx
  components/Domain/AddCloth/ColorModal/style.tsx
  components/Domain/MyPage/Closet/ClosetCloth/index.tsx
  components/Domain/MyPage/Closet/ClosetCloth/style.tsx
  components/Domain/MyPage/Closet/FilterModal/index.tsx
  components/Domain/MyPage/Closet/FilterModal/style.tsx
  components/Domain/MyPage/Profile/style.tsx
  components/Profile/OtherProfile/index.tsx
  components/Profile/OtherProfile/style.tsx
Labels: 🐞 버그

#166 옷 상세페이지 css 수정
  components/ActionSheet/index.tsx
  components/ActionSheet/style.tsx
  components/DetailCloth/ClothOOTD/index.tsx
  components/DetailCloth/ClothOOTD/style.tsx
  components/DetailCloth/DetailClothDiscription/index.tsx
  components/DetailCloth/DetailClothDiscription/style.tsx
  components/DetailCloth/SubHead/index.tsx
  components/DetailCloth/SubHead/style.tsx
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  pages/Cloth/[...ClothNumber].tsx
  style/DetailCloth/style.tsx
Labels: 🐞 버그

#168 마이페이지 필터 모달 반응형 추가
  components/ClothInformation/style.tsx
  components/Domain/AddOOTD/TagModal/style.tsx
  components/Domain/MyPage/Closet/ClosetCloth/style.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/index.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/style.tsx
  components/Domain/MyPage/Closet/FilterModal/style.tsx
  components/Domain/Search/SearchResult/ClosetCloth/style.tsx
  components/Modal/style.tsx
  public/images/Divider.svg
Labels: ⚙ 기능개발

#170 Carousel dots option 분기처리
  components/Carousel/index.tsx
  components/Domain/Main/MyCloset/index.tsx
  components/Domain/Main/TodayRecommend/index.tsx
  components/Domain/OOTD/UserCloth/index.tsx
  components/Domain/Search/SearchResult/FilterModal/index.tsx
  components/Gallery/index.tsx
  components/Posting/index.tsx
  components/TabView/Tabs/index.tsx
Labels: ⚙ 기능개발

#175 유저 정보 입력 관련 API 연동
  apis/_api/auth.ts
  apis/_api/type.ts
  apis/_service/auth.service.ts
  apis/domain/Register/RegisterApi.tsx
  components/Domain/SignUp/IdInput/index.tsx
  components/Domain/SignUp/StyleInput/index.tsx
  components/Input/CheckBox/index.tsx
  constants/business.constants.ts
  pages/AddOOTD/index.tsx
  pages/LikeInfo/index.tsx
  pages/sign-in/[...callback].tsx
  pages/sign-up/StyleInfo/index.tsx
  pages/sign-up/index.tsx
Labels: ⚙ 기능개발

#177 알림 페이지 구현
  components/Appbar/style.tsx
  components/Domain/Alarm/AlarmLayout/index.tsx
  components/Domain/Alarm/AlarmLayout/style.tsx
  components/Domain/Alarm/index.tsx
  components/Domain/Alarm/style.tsx
  pages/Alarm/index.tsx
  pages/main/index.tsx
  style/main/style.tsx
Labels: ⚙ 기능개발

#179 알림 API 연동 및 라우팅 추가
  apis/_api/alarm.ts
  apis/_api/index.ts
  apis/_service/user.service.ts
  apis/domain/Alarm/AlarmApi.tsx
  components/Domain/Alarm/NoAlarm/index.tsx
  components/Domain/Alarm/NoAlarm/style.tsx
  components/Domain/Alarm/index.tsx
  components/Domain/Alarm/style.tsx
  pages/Alarm/index.tsx
  pages/main/index.tsx
  style/main/style.tsx
Labels: ⚙ 기능개발

#184 Input 수정
  components/Input/ReadOnly/style.tsx
  components/Input/Text/index.tsx
  components/Input/Text/style.tsx
Labels: ⚙ 기능개발

#182 신고 관련 API 연동
  apis/_api/system.ts
  apis/_api/type.ts
  apis/_service/system.service.ts
  apis/domain/Report/ReportApi.tsx
  components/Comment/index.tsx
  components/DeclarationModal/index.tsx
  components/Posting/index.tsx
  components/ReceivedDeclarationModal/index.tsx
  components/ReceivedDeclarationModal/style.tsx
Labels: ⚙ 기능개발

#183 검색 관련 버그 수정
  components/DetailCloth/ClothOOTD/index.tsx
  components/DetailCloth/SubHead/index.tsx
  components/Domain/Search/Recents/index.tsx
  components/Domain/Search/Recents/style.tsx
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  components/Domain/Search/SearchResult/FilterModal/index.tsx
  components/Domain/Search/SearchResult/index.tsx
  pages/search/index.tsx
Labels: ⚙ 기능개발

#186 메인 페이지 수정
  components/Card/CardLayout/index.tsx
  components/Card/MainFavoriteCard/index.tsx
  components/Card/MainFavoriteCard/style.tsx
  components/Card/type.ts
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Domain/Main/LikeOOTD/index.tsx
  components/Domain/Main/LikeOOTD/style.tsx
  components/Domain/Main/SameCloth/index.tsx
  components/Domain/Main/TodayRecommend/index.tsx
  components/Domain/MyPage/Closet/FilterModal/index.tsx
  components/Domain/Search/SearchResult/FilterModal/index.tsx
  components/Posting/index.tsx
  components/Posting/style.tsx
  components/TabView/TabBar/index.tsx
  components/TabView/TabBar/style.tsx
  components/Toggle/LikeToggle/index.tsx
  pages/main/index.tsx
  style/main/style.tsx
Labels: ⚙ 기능개발

#187 좋아요 토글 버그 수정
  components/Posting/index.tsx
Labels: 🐞 버그

#181 마이페이지 프로필 관련 API 연동
  apis/_api/type.ts
  apis/_api/user.ts
  apis/_service/user.service.ts
  apis/domain/User/UserApi.tsx
  components/Domain/MyPage/BlockAlert/index.tsx
  components/Domain/MyPage/BlockAlert/style.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Domain/MyPage/Edit/EditMyInfo/index.tsx
  components/Domain/MyPage/Edit/EditMyInfo/style.tsx
  components/Domain/MyPage/Edit/EditProfile/index.tsx
  components/Domain/MyPage/Edit/EditProfile/style.tsx
  components/Domain/MyPage/Edit/index.tsx
  components/Domain/MyPage/Edit/style.tsx
  components/Domain/MyPage/Profile/index.tsx
  components/Domain/MyPage/Profile/style.tsx
  components/Profile/OtherProfile/index.tsx
  components/Profile/ProfileLayout/index.tsx
  components/Profile/ProfileLayout/style.tsx
  components/Toggle/SwitchToggle/style.tsx
  pages/mypage/[...UserId].tsx
  pages/mypage/index.tsx
Labels: ⚙ 기능개발

#189 이 옷을 활용한 OOTD API 연동
  apis/_api/ootd.ts
  apis/_service/user.service.ts
  apis/domain/Cloth/ClothApi.tsx
  components/DetailCloth/ClothOOTD/index.tsx
  pages/Cloth/[...ClothNumber].tsx
Labels: ⚙ 기능개발

#194 무한 스크롤 훅 구현
  AppLayout.tsx
  apis/_api/cloth.ts
  apis/_api/ootd.ts
  apis/_api/type.ts
  apis/_service/user.service.ts
  apis/domain/Cloth/ClothApi.tsx
  apis/domain/OOTD/OOTDApi.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/index.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/style.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Domain/MyPage/Closet/style.tsx
  components/Domain/OOTD/UserCloth/index.tsx
  components/Domain/OOTD/UserOtherOOTD/index.tsx
  components/ImageList/index.tsx
  components/PostingComment/index.tsx
  components/Spinner/index.tsx
  components/Spinner/style.tsx
  hooks/useInfiniteScroll.tsx
  package.json
  pages/OOTD/[...OOTDNumber].tsx
  yarn.lock
Labels: ⚙ 기능개발

#196 검색 페이지 최근 검색어
  AppLayout.tsx
  components/Domain/Search/Recents/index.tsx
  components/Domain/Search/SearchResult/index.tsx
  components/RecentsSearchBar/index.tsx
  components/RecentsSearchBar/style.tsx
  pages/search/index.tsx
Labels: ⚙ 기능개발

#210 ootd 상세페이지 수정
  apis/domain/OOTD/OOTDApi.tsx
  components/ActionSheet/style.tsx
  components/ClothInformation/TagInformation/index.tsx
  components/Domain/OOTD/FixModal/index.tsx
  components/Domain/OOTD/SimilarOOTD/index.tsx
  components/Domain/OOTD/UserCloth/index.tsx
  components/Domain/OOTD/UserOtherOOTD/index.tsx
  components/Domain/OOTD/UserOtherOOTD/style.tsx
  components/Posting/index.tsx
  pages/ootd/[...OOTDNumber].tsx
Labels: 🐞 버그, ⚙ 기능개발

#206 알림 페이지 수정
  apis/_api/alarm.ts
  apis/_api/type.ts
  apis/_service/user.service.ts
  apis/domain/Alarm/AlarmApi.tsx
  components/Domain/Alarm/index.tsx
  hooks/useInfiniteScroll.tsx
  pageStyle/alarm/style.tsx
  pages/Alarm/index.tsx
Labels: ⚙ 기능개발

#200 마이페이지 팔로워 팔로우 리스트 페이지 구현
  components/Domain/FollowList/FollowAlert/index.tsx
  components/Domain/FollowList/FollowAlert/style.tsx
  components/Domain/FollowList/Follower/index.tsx
  components/Domain/FollowList/Follower/style.tsx
  components/Domain/FollowList/Following/index.tsx
  components/Domain/FollowList/Following/style.tsx
  components/Domain/MyPage/Profile/index.tsx
  components/FollowBlock/index.tsx
  components/Profile/OtherProfile/index.tsx
  components/Profile/type.tsx
  components/TabView/TabBar/index.tsx
  components/TabView/TabBar/style.tsx
  pages/blocked-account/index.tsx
  pages/follow-list/[...UserId].tsx
  style/followList/style.tsx
Labels: ⚙ 기능개발

#213 Alert 재구현
  components/Alert/index.tsx
  components/Alert/style.tsx
  components/DetailCloth/DeleteAlert/index.tsx
  components/Domain/AddCloth/AddClothAlert/index.tsx
  components/Domain/Bookmark/BookmarkAlert/index.tsx
  components/Domain/FollowList/FollowAlert/index.tsx
  components/Domain/MyPage/BlockAlert/index.tsx
  components/Domain/OOTD/FixModal/index.tsx
  components/Gallery/index.tsx
  components/Setting/BlockAlert/index.tsx
  components/Setting/WithdrawAlert/index.tsx
  components/UI/TypoGraphy/Button1.tsx
  components/UI/TypoGraphy/Button3.tsx
Labels: ⚙ 기능개발

#214 북마크 페이지 API 연동
  apis/_api/ootd.ts
  components/Domain/Bookmark/BookmarkSubHead/index.tsx
  components/Domain/Bookmark/BookmarkSubHead/style.tsx
  components/ImageCheckBoxList/index.tsx
  pageStyle/bookmark/style.tsx
  pages/bookmark/index.tsx
  public/images/BookmarkCheckBoxFalse.png
  public/images/BookmarkCheckBoxTrue.png
Labels: ⚙ 기능개발

#218 ootd 등록 수정
  components/ClothInformation/TagInformation/style.tsx
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Domain/AddOOTD/TagModal/style.tsx
  components/Domain/OOTD/UserCloth/index.tsx
  components/Gallery/style.tsx
  pageStyle/add-ootd/ClothTag/style.tsx
  pageStyle/add-ootd/WriteOOTD/style.tsx
  pages/add-ootd/ClothTag/index.tsx
  pages/add-ootd/WriteOOTD/index.tsx
Labels: 🐞 버그, ⚙ 기능개발

#216 신고 관련 API 연동
  apis/domain/Report/ReportApi.tsx
  components/DeclarationModal/index.tsx
  pages/cloth/[...ClothNumber].tsx
Labels: ⚙ 기능개발

#224 마이페이지 관련 수정
  components/ActionSheet/index.tsx
  components/Domain/MyPage/BlockAlert/index.tsx
  components/Domain/MyPage/Closet/ClosetEmpty/index.tsx
  components/Domain/MyPage/Closet/ClosetEmpty/style.tsx
  components/Domain/MyPage/Closet/ClosetTabbar/index.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Domain/MyPage/OtherModal/index.tsx
  components/Domain/MyPage/Profile/index.tsx
  pageStyle/mypage/style.tsx
  pages/mypage/[...UserId].tsx
Labels: ⚙ 기능개발

#220 내 정보 수정 페이지 css 세부 사항 수정
  components/Domain/MyPage/Edit/EditMyInfo/index.tsx
  components/Domain/MyPage/Edit/EditMyInfo/style.tsx
  components/Domain/MyPage/Edit/EditProfile/index.tsx
  components/Domain/MyPage/Edit/index.tsx
  components/Domain/MyPage/Edit/style.tsx
  components/Input/Text/style.tsx
  pageStyle/edit-mypage/style.tsx
  pages/edit-mypage/index.tsx
Labels: 🐞 버그, ⚙ 기능개발

#222 옷 등록 관련 수정
  components/ClothCategory/index.tsx
  components/Domain/AddCloth/BrandModal/index.tsx
  components/Domain/AddCloth/BrandModal/style.tsx
  components/Domain/AddCloth/ClothCategoryModal/index.tsx
  components/Domain/AddCloth/ClothCategoryModal/style.tsx
  components/Domain/AddCloth/ColorModal/style.tsx
  components/Domain/AddCloth/WhereToBuyModal/index.tsx
  components/Domain/AddCloth/WhereToBuyModal/style.tsx
  components/Gallery/index.tsx
  components/Gallery/style.tsx
  pageStyle/add-cloth/BasicInfoFirst/style.tsx
  pageStyle/add-cloth/BasicInfoSecond/style.tsx
  pageStyle/add-cloth/ClothName/style.tsx
  pages/add-cloth/AdditionalInfo/index.tsx
  pages/add-cloth/BasicInfoFirst/index.tsx
  pages/add-cloth/BasicInfoSecond/index.tsx
  pages/add-cloth/index.tsx
Labels: 🐞 버그

#228 검색 API 연동 및 css 수정
  apis/_api/ootd.ts
  apis/_api/type.ts
  apis/_api/user.ts
  apis/_service/user.service.ts
  apis/domain/OOTD/OOTDApi.tsx
  apis/domain/User/UserApi.tsx
  components/Domain/Search/Recents/index.tsx
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  components/Domain/Search/SearchResult/ClosetCloth/style.tsx
  components/Domain/Search/SearchResult/FilterModal/index.tsx
  components/Domain/Search/SearchResult/FilterModal/style.tsx
  components/Domain/Search/SearchResult/Follow/index.tsx
  components/Domain/Search/SearchResult/Follow/style.tsx
  components/Domain/Search/SearchResult/Profile/index.tsx
  components/Domain/Search/SearchResult/Profile/style.tsx
  components/Domain/Search/SearchResult/SubHead/index.tsx
  components/Domain/Search/SearchResult/SubHead/style.tsx
  components/Domain/Search/SearchResult/index.tsx
  components/RecentsSearchBar/index.tsx
  pages/search/index.tsx
Labels: 🐞 버그, ⚙ 기능개발

#230 유저 정보 입력 관련 수정
  components/Domain/SignUp/AgeInput/index.tsx
  components/Domain/SignUp/BodyInput/index.tsx
  components/Domain/SignUp/IdInput/index.tsx
  components/Input/Text/style.tsx
  hooks/regex.ts
  pages/sign-up/BasicInfo/index.tsx
  pages/sign-up/BodyInfo/index.tsx
  pages/sign-up/index.tsx
Labels: 🐞 버그, ⚙ 기능개발

#236 마이페이지 수정 페이지 관련 수정
  components/Domain/MyPage/Edit/EditMyInfo/index.tsx
  components/Domain/MyPage/Edit/EditMyInfo/style.tsx
  components/Domain/MyPage/Edit/index.tsx
  components/Domain/MyPage/Edit/style.tsx
  components/Input/Text/index.tsx
  components/Input/Text/style.tsx
Labels: 🐞 버그

#232 탐색 컴포넌트 생성 및 API 연동
  components/Domain/Main/Explore/index.tsx
  components/Domain/Main/Explore/style.tsx
  components/Domain/Search/SearchResult/index.tsx
  pageStyle/bookmark/style.tsx
  pageStyle/main/style.tsx
  pages/main/index.tsx
Labels: ⚙ 기능개발

#237 검색 페이지 오류 수정
  apis/_api/ootd.ts
  components/Domain/Search/SearchResult/index.tsx
  components/RecentsSearchBar/index.tsx
Labels: 🐞 버그

#234 ootd 등록 관련 수정
  components/ClothInformation/TagInformation/index.tsx
  components/ClothInformation/type.ts
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Domain/AddOOTD/TagModal/style.tsx
  components/Gallery/index.tsx
  components/Gallery/style.tsx
  components/SearchBar/index.tsx
  components/Toast/index.tsx
  components/Toast/style.tsx
  pageStyle/add-ootd/ClothTag/style.tsx
  pages/add-ootd/ClothTag/index.tsx
Labels: ⚙ 기능개발

#239 스플래시 스크린 유저 아이디 API 연동 및 라우팅 설정
  apis/_api/auth.ts
  apis/_service/auth.service.ts
  apis/domain/Public/PublicApi.tsx
  next.config.js
  pages/onboarding/index.tsx
  pages/sign-in/[...callback].tsx
  pages/splash-screen/index.tsx
  utils/recoil/atom.tsx
Labels: ⚙ 기능개발

#241 마이페이지 관련 수정
  AppLayout.tsx
  apis/_api/user.ts
  apis/_service/user.service.ts
  apis/domain/MyPage/MyPageApi.tsx
  components/ColorList/index.tsx
  components/Domain/MyPage/Closet/ClosetCloth/index.tsx
  components/Domain/MyPage/Closet/ClosetCloth/style.tsx
  components/Domain/MyPage/Closet/FilterModal/index.tsx
  components/Domain/MyPage/Closet/FilterModal/style.tsx
  components/Domain/MyPage/Profile/index.tsx
  components/Profile/OtherProfile/index.tsx
  components/Profile/OtherProfile/style.tsx
  components/Profile/ProfileLayout/style.tsx
  components/TabView/TabBar/style.tsx
  components/TabView/index.tsx
  hooks/use-tabview/context.tsx
Labels: ⚙ 기능개발

#251 도메인 변경으로 인한 API 경로 변경
  apis/_api/alarm.ts
  apis/_api/auth.ts
  apis/_api/cloth.ts
  apis/_api/ootd.ts
  apis/_api/system.ts
  apis/_api/user.ts
  pages/_document.tsx
Labels: ✈ 환경세팅

#244 탐색 페이지 에러 수정
  components/Domain/Main/Explore/index.tsx
Labels: 🐞 버그

#247 유저의 옷 조회 API 검색 기능 추가
  apis/_api/cloth.ts
  apis/_api/type.ts
  components/Domain/AddOOTD/TagModal/index.tsx
Labels: ⚙ 기능개발
