Repository ootd-zip/client, pull requests merged in 2024-04, with the labels that each got.

#255 ootd 상세페이지 수정
  apis/_api/cloth.ts
  components/Comment/index.tsx
  components/Posting/index.tsx
  components/PostingComment/PostingCommentWrite/index.tsx
Labels: 🐞 버그

#253 취향 정보 수정 API 연동
  apis/_api/type.ts
  apis/_api/user.ts
  apis/_service/user.service.ts
  apis/domain/User/UserApi.tsx
  components/Domain/Setting/LikeInfo/index.tsx
  components/Domain/Setting/LikeInfo/style.tsx
  pages/like-info/index.tsx
  pages/settings/index.tsx
Labels: ⚙ 기능개발

#257 마이페이지 프로필 정보 조회 API 타입 수정
  components/Domain/MyPage/Closet/ClosetCloth/index.tsx
  components/Domain/MyPage/Profile/index.tsx
  components/Profile/ProfileLayout/index.tsx
  pages/mypage/[...UserId].tsx
Labels: 🐞 버그, ⚙ 기능개발

#254 북마크 관련 수정
  components/Domain/Bookmark/BookmarkSubHead/index.tsx
  components/Domain/Bookmark/BookmarkSubHead/style.tsx
  components/ImageCheckBoxList/index.tsx
  components/ImageCheckBoxList/style.tsx
  hooks/useInfiniteScroll.tsx
  pageStyle/bookmark/style.tsx
  pages/bookmark/index.tsx
  public/images/More.png
Labels: ⚙ 기능개발

#263 페이지 최대 넓이 추가 및 Next Image 도입
  components/BottomNavBar/AddModal/index.tsx
  components/BottomNavBar/style.tsx
  components/Button/style.tsx
  components/Comment/index.tsx
  components/Comment/style.tsx
  components/Domain/AddCloth/BrandModal/index.tsx
  components/Domain/MyPage/Closet/FilterModal/style.tsx
  components/Domain/MyPage/Edit/EditProfile/index.tsx
  components/Domain/OOTD/UserOtherOOTD/index.tsx
  components/Domain/OOTD/UserOtherOOTD/style.tsx
  components/Domain/Search/SearchResult/FilterModal/style.tsx
  components/Domain/Search/SearchResult/Profile/index.tsx
  components/EmptySearch/index.tsx
  components/Gallery/index.tsx
  components/Gallery/style.tsx
  components/Header/index.tsx
  components/ImageCheckBoxList/index.tsx
  components/ImageCheckBoxList/style.tsx
  components/ImageList/index.tsx
  components/ImageList/style.tsx
  components/Modal/style.tsx
  components/NextImage/index.tsx
  components/PlusButton/index.tsx
  components/Posting/index.tsx
  components/Posting/style.tsx
  components/PostingComment/PostingCommentWrite/index.tsx
  components/PostingComment/PostingCommentWrite/style.tsx
  components/PrevNextButton/style.tsx
  components/Profile/ProfileLayout/index.tsx
  pageStyle/add-cloth/AdditionalInfo/style.tsx
  pageStyle/add-cloth/BasicInfoSecond/style.tsx
  pageStyle/add-cloth/ClothName/style.tsx
  pageStyle/add-ootd/ClothTag/style.tsx
  pageStyle/add-ootd/WriteOOTD/style.tsx
  pageStyle/cloth/style.tsx
  pageStyle/edit-cloth/AdditionalInfo/style.tsx
  pageStyle/edit-cloth/BasicInfo/style.tsx
  pageStyle/edit-ootd/style.tsx
  pages/add-cloth/AdditionalInfo/index.tsx
  pages/add-cloth/BasicInfoFirst/index.tsx
  pages/add-cloth/BasicInfoSecond/index.tsx
  pages/add-cloth/ClothName/index.tsx
  pages/add-cloth/index.tsx
  pages/add-ootd/ClothTag/index.tsx
  pages/add-ootd/WriteOOTD/index.tsx
  pages/add-ootd/index.tsx
  pages/cloth/[...ClothNumber].tsx
  pages/edit-cloth/AdditionalInfo/index.tsx
  pages/edit-cloth/BasicInfo/index.tsx
  pages/edit-ootd/[...OOTDNumber].tsx
  pages/with-draw/index.tsx
  styles/GlobalStyle.tsx
Labels: ⚙ 기능개발

#266 검색 페이지 API 수정
  apis/_api/user.ts
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  components/Domain/Search/SearchResult/Profile/index.tsx
  components/Domain/Search/SearchResult/Profile/style.tsx
  components/Domain/Search/SearchResult/index.tsx
  components/ImageList/index.tsx
  components/ImageList/style.tsx
  components/RecentsSearchBar/style.tsx
  pages/with-draw/index.tsx
Labels: ⚙ 기능개발

#268 설정 페이지 구성
  components/Setting/SettingBlock/index.tsx
  components/Setting/SettingBlock/style.tsx
  pageStyle/like-info/style.tsx
  pageStyle/setting/style.tsx
  pages/like-info/index.tsx
  pages/settings/index.tsx
Labels: 💎UI 개발

#270 팔로워 팔로잉 관련 API 연동
  apis/_api/type.ts
  apis/_api/user.ts
  apis/_service/user.service.ts
  apis/domain/User/UserApi.tsx
  components/Domain/FollowList/FollowAlert/index.tsx
  components/Domain/FollowList/Follower/index.tsx
  components/Domain/FollowList/Follower/style.tsx
  components/Domain/FollowList/Following/index.tsx
  components/Domain/FollowList/Following/style.tsx
  components/Domain/Search/SearchResult/Profile/index.tsx
  components/Domain/Search/SearchResult/Profile/style.tsx
  components/Domain/Search/SearchResult/index.tsx
  pages/follow-list/[...UserId].tsx
  style/followList/style.tsx
Labels: ⚙ 기능개발

#249 애플 로그인 연동
  .env.template
  apis/domain/SignIn/SignInApi.tsx
  constants/develop.constants.ts
  pages/_app.tsx
  pages/sign-in/index.tsx
Labels: ⚙ 기능개발

#277 북마크 css 수정
  components/Domain/Bookmark/BookmarkSubHead/style.tsx
  components/ImageCheckBoxList/index.tsx
  components/ImageCheckBoxList/style.tsx
  pages/bookmark/index.tsx
Labels: 💎UI 개발

#272 Alert 관련 수정
  components/Alert/style.tsx
  components/Domain/Bookmark/BookmarkAlert/index.tsx
  pages/bookmark/index.tsx
Labels: ⚙ 기능개발

#274 로그인 페이지 수정
  pageStyle/sign-in/style.tsx
  pages/sign-in/index.tsx
Labels: ⚙ 기능개발

#276 유저 정보 입력 페이지 관련 수정
  components/Domain/SignUp/IdInput/index.tsx
  components/Domain/SignUp/IdInput/style.tsx
  pageStyle/sign-up/style.tsx
Labels: ⚙ 기능개발

#281 메인 페이지 수정
  apis/_api/ootd.ts
  apis/_service/user.service.ts
  apis/domain/Main/MainApi.tsx
  components/Card/CardLayout/index.tsx
  components/Card/MainFavoriteCard/index.tsx
  components/Card/type.ts
  components/Domain/Main/LikeOOTD/index.tsx
  components/Domain/Main/SameCloth/index.tsx
  components/Domain/Main/SameCloth/style.tsx
  components/UI/ImageWithCaption/index.tsx
  pageStyle/main/style.tsx
  pages/main/index.tsx
Labels: ⚙ 기능개발

#283 소셜 로그인 아이콘 변경
  components/Domain/SignIn/SocialLoginButton/index.tsx
  components/Domain/SignIn/SocialLoginButton/style.tsx
  public/images/appleLogo.png
  public/images/appleLogos.svg
  public/images/kakaoLogo.png
  public/images/kakaoLogos.svg
Labels: 🐞 버그

#286 의류 상세 페이지 css 수정
  components/DetailCloth/DetailClothDetailInfo/index.tsx
  components/DetailCloth/DetailClothDiscription/index.tsx
Labels: 💎UI 개발

#287 ootd 추가 페이지 css 수정
  components/Alert/style.tsx
  components/ClothInformation/TagInformation/index.tsx
  components/ClothInformation/TagInformation/style.tsx
  components/Domain/AddCloth/BrandModal/index.tsx
  components/Domain/AddOOTD/StyleModal/index.tsx
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Domain/AddOOTD/TagModal/style.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Input/CheckBox/index.tsx
  components/Input/CheckBox/style.tsx
  components/Input/TextArea/style.tsx
  components/Setting/WithdrawBlock/index.tsx
  pageStyle/add-ootd/ClothTag/style.tsx
  pageStyle/add-ootd/WriteOOTD/style.tsx
  pages/add-ootd/WriteOOTD/index.tsx
  public/images/CheckBoxFalse.png
  public/images/CheckBoxFalse.svg
  public/images/CheckBoxTrue.png
  public/images/CheckBoxTrue.svg
Labels: 🐞 버그

#291 디자인 시스템에 의한 Text Style 수정
  components/EmptySearch/index.tsx
  components/EmptySearch/style.tsx
  components/UI/TypoGraphy/Body2.tsx
  components/UI/TypoGraphy/Body3.tsx
  components/UI/TypoGraphy/Body4.tsx
  components/UI/TypoGraphy/Button2.tsx
  components/UI/TypoGraphy/Button3.tsx
  components/UI/TypoGraphy/Caption1.tsx
  components/UI/TypoGraphy/Caption2.tsx
  components/UI/TypoGraphy/Title1.tsx
  components/UI/TypoGraphy/Title2.tsx
  styles/font/lineHeight.ts
Labels: ✈ 환경세팅

#292 옷 추가 페이지 css 수정
  components/ClothCategory/style.tsx
  components/Domain/AddCloth/AddClothAlert/index.tsx
  components/Domain/AddCloth/BrandModal/index.tsx
  components/Domain/AddCloth/BrandModal/style.tsx
  components/Domain/AddCloth/ClothCategoryModal/index.tsx
  components/Domain/AddCloth/ClothCategoryModal/style.tsx
  components/Domain/AddCloth/ClothSizeModal/index.tsx
  components/Domain/AddCloth/ClothSizeModal/style.tsx
  components/Domain/AddCloth/ColorModal/index.tsx
  components/Domain/AddCloth/ColorModal/style.tsx
  components/Domain/AddCloth/WhereToBuyModal/index.tsx
  components/Domain/AddCloth/WhereToBuyModal/style.tsx
  components/Gallery/index.tsx
  components/Gallery/style.tsx
  components/Input/Modal/index.tsx
  components/Input/Modal/style.tsx
  components/Input/ReadOnly/style.tsx
  components/Input/Text/style.tsx
  components/Input/TextArea/index.tsx
  components/Input/TextArea/style.tsx
  components/PlusButton/style.tsx
  pageStyle/add-cloth/AdditionalInfo/style.tsx
  pageStyle/add-cloth/BasicInfoFirst/style.tsx
  pageStyle/add-ootd/WriteOOTD/style.tsx
  pages/add-cloth/AdditionalInfo/index.tsx
  pages/add-cloth/BasicInfoFirst/index.tsx
  pages/add-cloth/index.tsx
  pages/add-ootd/WriteOOTD/index.tsx
  public/images/ArrowLeft.svg
Labels: 🐞 버그

#294 로그인 관련 로직 수정
  .env.template
  apis/_api/auth.ts
  apis/_service/auth.service.ts
  apis/domain/SignIn/SignInApi.tsx
  constants/develop.constants.ts
  pages/sign-in/[...callback].tsx
Labels: ⚙ 기능개발

#295 로그인 메소드 수정
  apis/_api/auth.ts
Labels: ⚙ 기능개발

#297 dev 모드를 위한 환경 설정
  apis/domain/SignIn/SignInApi.tsx
  constants/develop.constants.ts
Labels: ✈ 환경세팅

#298 dev 모드를 위한 환경 설정
  constants/develop.constants.ts
Labels: ✈ 환경세팅

#300 마이페이지 css 수정
  components/BrandList/index.tsx
  components/Domain/MyPage/Closet/ClosetEmpty/index.tsx
  components/Domain/MyPage/Closet/FilterModal/index.tsx
  components/Domain/MyPage/Closet/FilterModal/style.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Domain/MyPage/Profile/index.tsx
  components/Domain/MyPage/Profile/style.tsx
  components/Profile/OtherProfile/index.tsx
  pages/mypage/[...UserId].tsx
Labels: 🐞 버그

#302 ootd 상세 페이지 css 수정
  components/Comment/index.tsx
  components/Comment/style.tsx
  components/Domain/OOTD/UserCloth/index.tsx
  components/NextImage/index.tsx
  components/Posting/index.tsx
  components/Posting/style.tsx
  components/PostingComment/PostingCommentWrite/index.tsx
  components/PostingComment/PostingCommentWrite/style.tsx
  components/PostingComment/index.tsx
  pages/ootd/[...OOTDNumber].tsx
  styles/colors/index.ts
Labels: 🐞 버그

#306 액세스토큰을 활용한 userId 조회 API 수정
  apis/_api/auth.ts
  pages/splash-screen/index.tsx
Labels: ⚙ 기능개발

#312 메인페이지 API 연동 및 초기 렌더링 컨텐츠 수정
  apis/_api/ootd.ts
  apis/_service/user.service.ts
  apis/domain/Main/MainApi.tsx
  components/Domain/Main/Explore/index.tsx
  components/Domain/Main/LikeOOTD/index.tsx
  components/Domain/Main/SameCloth/index.tsx
  components/Domain/Main/SameCloth/style.tsx
  next.config.js
  pages/main/[...main].tsx
  pages/main/index.tsx
  pages/ootd/[...OOTDNumber].tsx
Labels: ⚙ 기능개발

#304 ootd 수정 페이지 css 수정
  pageStyle/edit-ootd/style.tsx
  pages/edit-ootd/[...OOTDNumber].tsx
Labels: 🐞 버그, ⚙ 기능개발

#315 jwt 리프레시토큰 핸들링 로직 적용
  apis/_api/auth.ts
  apis/_service/auth.service.ts
  apis/domain/Public/PublicApi.tsx
  apis/domain/SignIn/SignInApi.tsx
  apis/fetcher.ts
  components/Gallery/index.tsx
  utils/recoil/atom.tsx
Labels: ⚙ 기능개발

#317 알림 페이지 버그 수정
  components/Domain/Alarm/index.tsx
  pages/Alarm/index.tsx
Labels: 🐞 버그

#318 검색 페이지 기능 개발 추가 작업
  components/Domain/Search/Recents/index.tsx
  components/RecentsSearchBar/index.tsx
  pages/search/index.tsx
Labels: ⚙ 기능개발

#314 신고 페이지 css 수정
  components/Comment/index.tsx
  components/Comment/style.tsx
  components/DeclarationModal/index.tsx
  components/DeclarationModal/style.tsx
  components/Posting/index.tsx
  components/PostingComment/index.tsx
  components/ReceivedDeclarationModal/index.tsx
  components/ReceivedDeclarationModal/style.tsx
  components/Setting/WithdrawBlock/index.tsx
  components/Setting/WithdrawBlock/style.tsx
  pageStyle/ootd/style.tsx
  pages/cloth/[...ClothNumber].tsx
  pages/ootd/[...OOTDNumber].tsx
Labels: 💎UI 개발

#320 마이페이지 수정 페이지 css
  components/Domain/MyPage/Edit/EditProfile/index.tsx
Labels: 💎UI 개발

#327 검색 css 수정
  components/Domain/Search/Recents/style.tsx
  components/Domain/Search/SearchResult/index.tsx
  components/EmptySearch/style.tsx
  components/RecentsSearchBar/style.tsx
Labels: 💎UI 개발

#323 댓글 신고 Modal 기능 수정
  components/Comment/index.tsx
  components/PostingComment/index.tsx
Labels: 🐞 버그

#325 북마크 css 수정
  components/Domain/Bookmark/BookmarkSubHead/style.tsx
  pageStyle/bookmark/style.tsx
  pages/bookmark/index.tsx
Labels: 💎UI 개발

#330 하단 네비게이션 바 Link 처리
  components/BottomNavBar/index.tsx
  components/BottomNavBar/style.tsx
Labels: ⚙ 기능개발

#332 refreshToken 만료 시 비동기 함수가 여러개인 경우 버그 수정
  apis/fetcher.ts
Labels: 🐞 버그

#334 네이버 로그인 추가
  apis/domain/SignIn/SignInApi.tsx
  components/Domain/SignIn/SocialLoginButton/index.tsx
  components/Domain/SignIn/SocialLoginButton/style.tsx
  constants/develop.constants.ts
  pages/sign-in/index.tsx
  public/images/naverLogo.svg
Labels: ⚙ 기능개발

#322 마이페이지 유저 정보 입력 관련 수정
  components/Domain/MyPage/Edit/EditMyInfo/index.tsx
  components/Domain/MyPage/Edit/EditMyInfo/style.tsx
Labels: ⚙ 기능개발

#336 개인정보 처리 방침 페이지 구성
  pageStyle/privacy-policy/style.tsx
  pages/privacy-policy/index.tsx
  pages/settings/index.tsx
Labels: 💎UI 개발

#342 만료된 accessToken 전송 시 오류가 나는 버그 수정
  apis/_api/auth.ts
Labels: 🐞 버그

#344 중복 신고 모달 API 변동
  apis/domain/Report/ReportApi.tsx
  components/DeclarationModal/index.tsx
  components/ReceivedDeclarationModal/style.tsx
Labels: ⚙ 기능개발

#345 로그인 플랫폼 API 연동
  apis/_api/user.ts
  apis/_service/user.service.ts
  apis/domain/User/UserApi.tsx
  pages/settings/index.tsx
Labels: ⚙ 기능개발

#347 jwt 토큰 저장소 변경
  apis/_api/auth.ts
  apis/domain/Public/PublicApi.tsx
  apis/domain/SignIn/SignInApi.tsx
  apis/fetcher.ts
  components/Gallery/index.tsx
  pages/splash-screen/index.tsx
Labels: ⚙ 기능개발

#350 ootd 작성 시 태그 오류 수정
  components/ClothInformation/TagInformation/style.tsx
Labels: 🐞 버그

#353 백그라운드 컴포넌트화
  AppLayout.tsx
  components/Background/index.tsx
  components/Background/style.tsx
  components/Comment/index.tsx
  components/Comment/style.tsx
  components/Domain/AddOOTD/StyleModal/style.tsx
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Domain/AddOOTD/TagModal/style.tsx
  components/Domain/MyPage/Closet/ClosetCloth/index.tsx
  components/Domain/MyPage/Closet/ClosetCloth/style.tsx
  components/Domain/OOTD/FixModal/index.tsx
  components/Domain/OOTD/FixModal/style.tsx
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  components/Domain/Search/SearchResult/ClosetCloth/style.tsx
  components/Gallery/index.tsx
  components/Gallery/style.tsx
  components/Posting/index.tsx
  components/Posting/style.tsx
  pageStyle/add-cloth/BasicInfoFirst/style.tsx
  pageStyle/add-cloth/BasicInfoSecond/style.tsx
  pageStyle/add-ootd/ClothTag/style.tsx
  pageStyle/add-ootd/WriteOOTD/style.tsx
  pageStyle/blocked-account/style.tsx
  pageStyle/bookmark/style.tsx
  pageStyle/cloth/style.tsx
  pageStyle/edit-cloth/BasicInfo/style.tsx
  pageStyle/edit-mypage/style.tsx
  pageStyle/edit-ootd/style.tsx
  pageStyle/mypage/style.tsx
  pageStyle/ootd/style.tsx
  pageStyle/with-draw/style.tsx
  pages/add-cloth/BasicInfoFirst/index.tsx
  pages/add-cloth/BasicInfoSecond/index.tsx
  pages/add-ootd/ClothTag/index.tsx
  pages/add-ootd/WriteOOTD/index.tsx
  pages/blocked-account/index.tsx
  pages/bookmark/index.tsx
  pages/cloth/[...ClothNumber].tsx
  pages/edit-cloth/BasicInfo/index.tsx
  pages/edit-mypage/index.tsx
  pages/edit-ootd/[...OOTDNumber].tsx
  pages/follow-list/[...UserId].tsx
  pages/mypage/[...UserId].tsx
  pages/ootd/[...OOTDNumber].tsx
  pages/with-draw/index.tsx
  style/followList/style.tsx
Labels: 🚧 리팩토링

#355 최근 검색어 중복 제거
  components/Domain/Search/Recents/index.tsx
  pages/search/index.tsx
Labels: ⚙ 기능개발

#358 차단 관련 임시 수정
  components/ReceivedDeclarationModal/index.tsx
  pages/mypage/[...UserId].tsx
  pages/settings/index.tsx
Labels: ⚙ 기능개발

#359 로그아웃 api 연동
  apis/_api/auth.ts
  apis/_service/auth.service.ts
  apis/domain/User/UserApi.tsx
  pages/settings/index.tsx
Labels: ⚙ 기능개발

#361 같은 옷 다른 느낌 api 수정
  apis/_api/ootd.ts
  components/Domain/Main/SameCloth/index.tsx
Labels: 🚧 리팩토링

#363 옷 정보 태그 수정
  components/ClothInformation/TagInformation/style.tsx
  pageStyle/add-ootd/ClothTag/style.tsx
Labels: 🐞 버그

#365 옷 카테고리 수정 버그 수정
  components/ClothCategory/index.tsx
Labels: 🐞 버그

#366 읽지 않은 알림 표기 추가
  components/Domain/Alarm/index.tsx
  pageStyle/alarm/style.tsx
  pages/Alarm/index.tsx
Labels: ⚙ 기능개발

#368 같은 옷 다른 느낌 api 버그 수정
  components/Domain/Main/SameCloth/index.tsx
Labels: 🐞 버그

#370 옷 페이지 관련 수정
  apis/_api/cloth.ts
  apis/_api/type.ts
  apis/_service/user.service.ts
  apis/domain/Cloth/ClothApi.tsx
  components/DetailCloth/DeleteAlert/index.tsx
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Domain/OOTD/UserCloth/index.tsx
  pages/cloth/[...ClothNumber].tsx
  pages/ootd/[...OOTDNumber].tsx
Labels: ⚙ 기능개발

#373 ootd 등록 페이지 옷 태그 정보 표기 안되는 버그 수정
  components/Domain/AddOOTD/TagModal/index.tsx
Labels: 🐞 버그
