Repository ootd-zip/client, pull requests merged in 2024-08, with the labels that each got.

#517 브랜드 건의
  apis/_api/system.ts
  apis/_api/type.ts
  apis/_service/system.service.ts
  apis/domain/Cloth/ClothApi.tsx
  components/Domain/AddCloth/BrandModal/index.tsx
  components/Domain/AddCloth/BrandModal/style.tsx
  components/Toast/style.tsx
  pages/add-cloth/BasicInfoFirst/index.tsx
Labels: ⚙ 기능개발

#523 옷 추가 과정 간소화 및 이미지 base64 인코딩
  apis/_api/type.ts
  components/ColorList/BigColor/index.tsx
  components/ColorList/BigColor/style.tsx
  components/ColorList/MiniColor/index.tsx
  components/ColorList/MiniColor/style.tsx
  components/ColorList/index.tsx
  components/Domain/AddCloth/RecommendColor/index.tsx
  components/Domain/AddCloth/RecommendColor/style.tsx
  components/Gallery/index.tsx
  components/Input/TrueFalse/style.tsx
  hooks/useRememberScroll.tsx
  next.config.js
  pageStyle/add-cloth/AdditionalInfo/style.tsx
  pageStyle/add-cloth/BasicInfoFirst/style.tsx
  pages/add-cloth/AdditionalInfo/index.tsx
  pages/add-cloth/BasicInfoFirst/index.tsx
  pages/add-cloth/BasicInfoSecond/index.tsx
  pages/add-cloth/ClothName/index.tsx
  pages/add-cloth/index.tsx
  pages/add-ootd/WriteOOTD/index.tsx
  pages/add-ootd/index.tsx
  pages/edit-cloth/AdditionalInfo/index.tsx
  pages/edit-cloth/BasicInfo/index.tsx
  pages/edit-cloth/[...ClothNumber].tsx
  utils/reactNativeMessage.ts
Labels: ⚙ 기능개발

#525 당겨서 새로 고침 기능 구현
  apis/domain/Public/PublicApi.tsx
  components/Domain/FollowList/Follower/index.tsx
  components/Domain/FollowList/Following/index.tsx
  components/Domain/Main/Explore/index.tsx
  components/Domain/Main/Explore/style.tsx
  components/Domain/MyPage/Closet/ClosetCloth/index.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/index.tsx
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  components/Domain/Search/SearchResult/Profile/index.tsx
  components/Domain/Search/SearchResult/index.tsx
  hooks/useInfiniteScroll.tsx
  pages/follow-list/[...UserId].tsx
Labels: 🐞 버그, ⚙ 기능개발

#527 색상 추출 리팩토링
  components/Gallery/index.tsx
  utils/ColorExtraction.ts
  yarn.lock
Labels: 🚧 리팩토링
