Repository ootd-zip/client, pull requests merged in 2024-05, with the labels that each got.

#375 리프레시 토큰 만료 시 로그인 화면으로 이동
  apis/domain/Public/PublicApi.tsx
Labels: ⚙ 기능개발

#377 최대 확대 범위 1로 고정
  pages/_app.tsx
Labels: ⚙ 기능개발

#379 마이페이지 추가 버튼 폰트 색상 변경
  components/Domain/MyPage/Closet/ClosetEmpty/index.tsx
  components/Domain/MyPage/Closet/ClosetEmpty/style.tsx
Labels: ⚙ 기능개발

#382 앱 자동 로그인 추가
  apis/domain/Public/PublicApi.tsx
  apis/domain/SignIn/SignInApi.tsx
  apis/domain/User/UserApi.tsx
  components/Gallery/index.tsx
  pages/sign-in/[...callback].tsx
  pages/splash-screen/index.tsx
  utils/reactNativeMessage.ts
Labels: ⚙ 기능개발

#394 최근 검색어 공란 값 없애기
  pages/search/index.tsx
Labels: ⚙ 기능개발

#393 북마크 svg 수정
  components/BottomNavBar/index.tsx
Labels: ⚙ 기능개발

#385 mypage 라우팅 오류 수정
  pages/mypage/[...UserId].tsx
Labels: ⚙ 기능개발

#395 안드로이드 키보드 활성화 시 뷰포트 변환에 따른 fixed 버튼 대응
  components/Domain/AddCloth/WhereToBuyModal/index.tsx
  components/Domain/AddCloth/WhereToBuyModal/style.tsx
  components/Domain/MyPage/Edit/index.tsx
  components/Domain/MyPage/Edit/style.tsx
  pageStyle/add-cloth/AdditionalInfo/style.tsx
  pageStyle/add-cloth/ClothName/style.tsx
  pageStyle/edit-cloth/AdditionalInfo/style.tsx
  pageStyle/edit-ootd/style.tsx
  pageStyle/sign-up/style.tsx
  pages/add-cloth/AdditionalInfo/index.tsx
  pages/add-cloth/ClothName/index.tsx
  pages/edit-ootd/[...OOTDNumber].tsx
Labels: 🐞 버그

#396 ootd 상세 페이지 관련 수정
  components/Comment/style.tsx
  components/Domain/OOTD/UserCloth/index.tsx
Labels: 🐞 버그

#397 input 최대 길이 수정
  components/Input/Text/style.tsx
Labels: ⚙ 기능개발

#401 ootd 추가 페이지 관련 수정
  components/Domain/AddOOTD/TagModal/index.tsx
  components/Gallery/index.tsx
  pages/add-cloth/index.tsx
  pages/add-ootd/index.tsx
Labels: ⚙ 기능개발

#406 mypage 라우팅 다중 호출 에러
  pages/mypage/[...UserId].tsx
Labels: 🐞 버그

#407 toast 메시지 호출 에러
  components/Toast/index.tsx
  pages/mypage/[...UserId].tsx
  pages/settings/index.tsx
Labels: 🐞 버그

#409 에러 바운더리를 활용한 에러 핸들링 로직 추가
  apis/domain/Alarm/AlarmApi.tsx
  apis/domain/Bookmark/BookmarkApi.tsx
  apis/domain/Cloth/ClothApi.tsx
  apis/domain/Main/MainApi.tsx
  apis/domain/MyPage/MyPageApi.tsx
  apis/domain/OOTD/OOTDApi.tsx
  apis/domain/Public/PublicApi.tsx
  apis/domain/Register/RegisterApi.tsx
  apis/domain/SignIn/SignInApi.tsx
  apis/domain/User/UserApi.tsx
  apis/fetcher.ts
  components/BottomNavBar/index.tsx
  components/MyErrorBoundary/ErrorLayout/index.tsx
  components/MyErrorBoundary/ErrorLayout/style.tsx
  components/MyErrorBoundary/index.tsx
  package.json
  pages/404.tsx
  pages/_app.tsx
  pages/ootd/[...OOTDNumber].tsx
  tsconfig.json
  yarn.lock
Labels: ⚙ 기능개발

#411 이미지 로딩중 띄울 블러 이미지 추가
  components/NextImage/index.tsx
  components/UI/ImageWithCaption/index.tsx
Labels: ✈ 환경세팅

#414 에러 바운더리 관련 머지 에러 해결
  components/MyErrorBoundary/ErrorLayout/index.tsx
Labels: 🐞 버그

#416 내가 찜한 ootd 라우터 경로 오류 수정
  components/Card/MainFavoriteCard/index.tsx
Labels: 🐞 버그

#417 공지사항 페이지 구현
  components/BottomNavBar/index.tsx
  components/Setting/AnnouncementBlock/index.tsx
  components/Setting/AnnouncementBlock/style.tsx
  pages/announcement/index.tsx
  pages/settings/index.tsx
Labels: ⚙ 기능개발

#420 Z-index 통일화
  AppLayout.tsx
  components/ActionSheet/style.tsx
  components/Alert/style.tsx
  components/Background/style.tsx
  components/BottomNavBar/AddModal/style.tsx
  components/ClothInformation/TagInformation/style.tsx
  components/Domain/AddCloth/ColorModal/style.tsx
  components/Domain/Alarm/style.tsx
  components/Domain/Bookmark/BookmarkSubHead/style.tsx
  components/Domain/Main/Explore/style.tsx
  components/Domain/MyPage/Closet/FilterModal/style.tsx
  components/Gallery/style.tsx
  components/ImageCheckBoxList/style.tsx
  components/ImageList/style.tsx
  components/Modal/style.tsx
  components/Posting/style.tsx
  components/Spinner/style.tsx
  pageStyle/add-cloth/BasicInfoSecond/style.tsx
  pageStyle/bookmark/style.tsx
  pageStyle/edit-ootd/style.tsx
Labels: ✈ 환경세팅

#422 카카오 로그인 간편 로그인으로 변경
  apis/_api/auth.ts
  apis/domain/SignIn/SignInApi.tsx
  apis/fetcher.ts
Labels: ⚙ 기능개발

#423 차단 API 연동 및 컴포넌트 재구성
  apis/_api/block.ts
  apis/_api/index.ts
  apis/_api/type.ts
  apis/_service/user.service.ts
  apis/domain/Block/BlockApi.tsx
  components/Comment/index.tsx
  components/Domain/BlockUser/BlockUserAlert/index.tsx
  components/Domain/BlockUser/BlockUserAlert/style.tsx
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  components/Domain/Search/SearchResult/Profile/index.tsx
  components/Posting/index.tsx
  components/PostingComment/index.tsx
  components/ReceivedDeclarationModal/index.tsx
  pageStyle/blocked-account/style.tsx
  pages/blocked-account/index.tsx
  pages/cloth/[...ClothNumber].tsx
  pages/main/[...main].tsx
  pages/mypage/[...UserId].tsx
  pages/ootd/[...OOTDNumber].tsx
  pages/search/index.tsx
  pages/settings/index.tsx
Labels: ⚙ 기능개발

#419 이용 약관 동의 페이지 구성
  components/AgreeBlock/index.tsx
  components/AgreeBlock/style.tsx
  pageStyle/agree/style.tsx
  pages/agree-policy/index.tsx
  pages/agree/index.tsx
  pages/privacy-policy/index.tsx
  pages/splash-screen/index.tsx
  public/images/symbol.svg
Labels: 💎UI 개발

#424 카카오 로그인 리다이렉트 경로 수정
  constants/develop.constants.ts
Labels: ⚙ 기능개발

#426 댓글 신고 중첩 모달 버그 수정
  components/Comment/index.tsx
  components/PostingComment/index.tsx
  constants/develop.constants.ts
Labels: 🐞 버그

#428 네이버, 애플 로그인 api 경로 수정
  apis/_api/auth.ts
Labels: 🐞 버그

#430 이용약관 페이지 바로가기 추가
  constants/develop.constants.ts
  pages/settings/index.tsx
Labels: ⚙ 기능개발

#432 메인 페이지 기본 컨텐츠 변경
  components/BottomNavBar/index.tsx
  next.config.js
  pages/mypage/[...UserId].tsx
Labels: 🚧 리팩토링

#435 styled-component의 깜빡거리는 현상제거
  .babelrc
  package.json
  pages/_document.tsx
  public/images/권낙현.jpg
  public/images/권낙현2.jpg
  public/images/권낙현3.jpg
  public/images/권재형.jpg
  public/images/김주엽.jpg
  public/images/박윤욱.jpg
  public/images/손정민.jpg
  yarn.lock
Labels: 🚧 리팩토링

#437 메인 탐색 페이지 스크롤 수정
  components/Domain/Main/Explore/style.tsx
Labels: 🐞 버그

#440 옷 태그 최대 길이 설정
  components/ClothInformation/TagInformation/style.tsx
Labels: 🐞 버그

#441 브랜드 선택안함이 나이키로 매칭되는 오류 수정
  components/Domain/AddCloth/BrandModal/index.tsx
Labels: 🐞 버그

#443 팔로우 팔로잉 페이지 인원이 제대로 표시 되지 않는 이슈
  components/Domain/FollowList/Follower/index.tsx
  components/Domain/FollowList/Following/index.tsx
Labels: 🐞 버그

#445 프로필 수정 에러
  components/Domain/MyPage/Edit/EditMyInfo/index.tsx
  components/Domain/MyPage/Edit/index.tsx
Labels: 🐞 버그

#448 옷 상세 페이지 구매 링크 이동
  components/DetailCloth/DetailClothDiscription/index.tsx
Labels: ⚙ 기능개발

#452 옷 상세 페이지 구매링크 가로 너비 처리
  components/DetailCloth/DetailClothDiscription/style.tsx
Labels: 🐞 버그
