Repository ootd-zip/client, pull requests merged in 2024-06, with the labels that each got.

#454 스크롤 관련 이슈 처리
  components/Carousel/index.tsx
  components/Domain/Main/Explore/index.tsx
  components/Domain/MyPage/Closet/ClosetCloth/index.tsx
  components/Domain/MyPage/Closet/ClosetCloth/style.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/index.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/style.tsx
  components/Domain/MyPage/Closet/ClosetTabbar/index.tsx
  components/Domain/MyPage/Closet/ClosetTabbar/style.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Domain/Search/SearchResult/ClosetCloth/index.tsx
  components/Domain/Search/SearchResult/index.tsx
  components/TabView/TabBar/index.tsx
  components/TabView/Tabs/index.tsx
  hooks/useInfiniteScroll.tsx
  hooks/useRememberScroll.tsx
  next.config.js
  package-lock.json
  package.json
  pages/_app.tsx
  pages/bookmark/index.tsx
  pages/cloth/[...ClothNumber].tsx
  pages/main/[...main].tsx
  pages/mypage/[...UserId].tsx
  yarn.lock
Labels: ⚙ 기능개발

#456 의류 상세 페이지 공개 비공개 표기 변경
  components/DetailCloth/DetailClothHeader/index.tsx
  pages/cloth/[...ClothNumber].tsx
Labels: ⚙ 기능개발

#460 FAB 버튼 위치 조정
  components/Domain/Main/Explore/style.tsx
  pageStyle/bookmark/style.tsx
Labels: 💎UI 개발

#464 merge
  components/DetailCloth/DetailClothDiscription/style.tsx
  components/DetailCloth/DetailClothHeader/index.tsx
  pages/cloth/[...ClothNumber].tsx
Labels: ⚙ 기능개발

#472 같은 옷 다른 느낌 옷 정보 최대 길이 수정
  components/Domain/Main/SameCloth/index.tsx
  components/Domain/Main/SameCloth/style.tsx
Labels: 🐞 버그

#473 옷, ootd 추가 관련 수정
  components/Domain/AddCloth/BrandModal/style.tsx
  components/Domain/AddOOTD/StyleModal/index.tsx
  components/Gallery/style.tsx
  pageStyle/add-ootd/WriteOOTD/style.tsx
  pages/add-cloth/BasicInfoFirst/index.tsx
  pages/add-ootd/ClothTag/index.tsx
  pages/add-ootd/WriteOOTD/index.tsx
  utils/reactNativeMessage.ts
Labels: 🐞 버그, ⚙ 기능개발

#462 최근 검색어 chip 순서 변경
  components/Domain/Bookmark/BookmarkSubHead/index.tsx
  components/Domain/Bookmark/BookmarkSubHead/style.tsx
  components/Domain/Main/Explore/style.tsx
  pageStyle/bookmark/style.tsx
  pages/search/index.tsx
Labels: ⚙ 기능개발

#474 옷 상세보기 페이지 수정
  components/Domain/OOTD/UserCloth/index.tsx
  components/Domain/OOTD/UserCloth/style.tsx
  components/Domain/OOTD/UserOtherOOTD/index.tsx
  components/Posting/index.tsx
Labels: ⚙ 기능개발

#482 세션 스토리지가 초기화 되는 조건 추가
  apis/domain/User/UserApi.tsx
  components/BottomNavBar/index.tsx
  components/RecentsSearchBar/index.tsx
  hooks/useRememberScroll.tsx
Labels: 🐞 버그

#483 merge
  apis/domain/User/UserApi.tsx
  components/BottomNavBar/index.tsx
  components/RecentsSearchBar/index.tsx
  hooks/useRememberScroll.tsx
Labels: ⚙ 기능개발

#485 dev 셋팅
  constants/develop.constants.ts
Labels: ✈ 환경세팅

#487 최근 검색어 chip 폰트 웨이트 상이
  components/DetailCloth/DetailClothDetailInfo/style.tsx
  components/Domain/Search/Recents/index.tsx
  constants/develop.constants.ts
  pages/search/index.tsx
Labels: 💎UI 개발

#489 OOTD 좋아요 개수 추가
  components/Posting/index.tsx
  components/Posting/style.tsx
Labels: ⚙ 기능개발

#493 마이페이지 버그 수정
  components/Domain/MyPage/Closet/ClosetOOTD/index.tsx
  components/Domain/MyPage/Closet/index.tsx
Labels: 🐞 버그

#497 탐색 페이지 ootd 총 게시물 개수 표기 오류 수정
  components/Domain/Main/Explore/index.tsx
Labels: 🐞 버그

#495 ootd 등록 시 태그 건너뛰기 기능 구현
  pages/add-ootd/ClothTag/index.tsx
  pages/add-ootd/index.tsx
Labels: ⚙ 기능개발

#498 merge
  components/DetailCloth/DetailClothDetailInfo/style.tsx
  components/Domain/Main/Explore/index.tsx
  components/Domain/MyPage/Closet/ClosetOOTD/index.tsx
  components/Domain/MyPage/Closet/index.tsx
  components/Domain/MyPage/Edit/EditMyInfo/style.tsx
  components/Domain/MyPage/Edit/EditProfile/index.tsx
  components/Domain/Search/Recents/index.tsx
  components/Posting/index.tsx
  components/Posting/style.tsx
  constants/develop.constants.ts
  pages/add-ootd/ClothTag/index.tsx
  pages/add-ootd/index.tsx
  pages/search/index.tsx
Labels: 🐞 버그, ⚙ 기능개발
