Repository ootd-zip/client, pull requests merged in 2024-07, with the labels that each got.

#505 스타일 태그 검색
  components/Posting/index.tsx
Labels: ⚙ 기능개발

#509 FAB와 Toast의 충돌
  components/Toast/index.tsx
  components/Toast/style.tsx
  pageStyle/bookmark/style.tsx
  pages/bookmark/index.tsx
Labels: ⚙ 기능개발

#515 태그한 유저의 휴대폰 크기보다 작은 휴대폰에서의 태그가 안보이는 버그
  components/Posting/index.tsx
Labels: 🐞 버그

#516 이미지 색상 추출
  components/AgreeBlock/index.tsx
  components/DeclarationModal/index.tsx
  components/Gallery/index.tsx
  components/NextImage/index.tsx
  components/Portal/index.tsx
  components/Setting/WithdrawBlock/index.tsx
  pages/add-cloth/index.tsx
  pages/agree/index.tsx
  pages/with-draw/index.tsx
  utils/ColorExtraction.ts
Labels: ⚙ 기능개발

#500 native 메시지 송수신 리팩토링
  utils/reactNativeMessage.ts
Labels: 🚧 리팩토링
